# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target',
            new_name='related_issue',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='target',
            new_name='related_issue',
        ),
        migrations.AlterField(
            model_name='issue',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('IC', 'Incomplete'), ('IP', 'Inprogress'), ('CT', 'Complete')], default='IC', max_length=2),
        ),
    ]
