# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190425_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
